# Generated by Django 4.2.19 on 2026-02-05 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('color', models.CharField(choices=[('primary', 'Primary'), ('danger', 'Danger'), ('success', 'Success'), ('warning', 'Warning'), ('info', 'Info'), ('secondary', 'Secondary')], default='primary', max_length=20, verbose_name='Color')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='Excerpt')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Full Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Image')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Image URL or Path')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Publication Date')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='main.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
