# Generated by Django 4.2.19 on 2026-02-06 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_article_image_url_alter_article_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('replied', 'Répondu'), ('archived', 'Archivé')], default='new', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message de Contact',
                'verbose_name_plural': 'Messages de Contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('talk', 'Talk Show'), ('music', 'Music & Culture'), ('sports', 'Sports'), ('interview', 'Interviews'), ('dj', 'DJ Mixes')], max_length=50, unique=True, verbose_name='Category Name')),
                ('icon', models.CharField(default='fas fa-podcast', help_text='e.g., fas fa-comments', max_length=50, verbose_name='FontAwesome Icon')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Podcast Category',
                'verbose_name_plural': 'Podcast Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PodcastShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Show Title')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.URLField(verbose_name='Cover Image URL')),
                ('badge', models.CharField(choices=[('new', 'NEW'), ('weekly', 'WEEKLY'), ('featured', 'FEATURED'), ('none', 'None')], default='none', max_length=20, verbose_name='Badge')),
                ('total_episodes', models.IntegerField(default=0, verbose_name='Total Episodes')),
                ('average_duration', models.CharField(default='30 min', help_text='e.g., 30-45 min or just 30 min', max_length=50, verbose_name='Average Duration')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Show')),
                ('featured_title', models.CharField(blank=True, help_text='Custom title for featured section', max_length=200, null=True, verbose_name='Featured Title')),
                ('featured_description', models.TextField(blank=True, help_text='Description for featured section', null=True, verbose_name='Featured Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('listen_count', models.IntegerField(default=0, verbose_name='Total Listens')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='main.podcastcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Podcast Show',
                'verbose_name_plural': 'Podcast Shows',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Episode Title')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(verbose_name='Episode Description')),
                ('episode_number', models.IntegerField(verbose_name='Episode Number')),
                ('audio_url', models.URLField(help_text='Link to MP3/audio file', verbose_name='Audio File URL')),
                ('duration', models.CharField(default='00:00', help_text='Format: MM:SS or HH:MM:SS', max_length=20, verbose_name='Duration')),
                ('file_size', models.CharField(blank=True, help_text='e.g., 25.5 MB', max_length=20, null=True, verbose_name='File Size')),
                ('cover_image', models.URLField(blank=True, help_text='If blank, uses show image', null=True, verbose_name='Episode Cover Image')),
                ('published_date', models.DateTimeField(verbose_name='Published Date')),
                ('season_number', models.IntegerField(blank=True, null=True, verbose_name='Season Number')),
                ('guest', models.CharField(blank=True, max_length=200, null=True, verbose_name='Guest(s)')),
                ('host', models.CharField(blank=True, max_length=100, null=True, verbose_name='Host')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='Transcript')),
                ('show_notes', models.TextField(blank=True, null=True, verbose_name='Show Notes')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200, null=True, verbose_name='Tags')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Episode')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('listen_count', models.IntegerField(default=0, verbose_name='Listen Count')),
                ('download_count', models.IntegerField(default=0, verbose_name='Download Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='main.podcastshow', verbose_name='Podcast Show')),
            ],
            options={
                'verbose_name': 'Podcast Episode',
                'verbose_name_plural': 'Podcast Episodes',
                'ordering': ['-published_date', '-episode_number'],
                'unique_together': {('show', 'episode_number')},
            },
        ),
    ]
