# Generated by Django 4.2.19 on 2026-02-07 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactmessage_podcastcategory_podcastshow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ad Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Ad Image')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('link_url', models.URLField(blank=True, help_text='Where ad redirects when clicked', null=True, verbose_name='Link URL')),
                ('position', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('Summary', models.TextField(verbose_name='Summary')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='Image')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Image')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Publication Date')),
                ('link', models.CharField(max_length=200, verbose_name='Link to Article')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('title', models.CharField(max_length=200, verbose_name='Title/Function')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teams/', verbose_name='Photo')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Image or Path')),
                ('whatsapp_url', models.URLField(blank=True, null=True, verbose_name='WhatsApp')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('order', models.IntegerField(default=0, verbose_name='Order of Display')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Article Category', 'verbose_name_plural': 'Article Categories'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.RemoveField(
            model_name='podcastshow',
            name='average_duration',
        ),
        migrations.RemoveField(
            model_name='podcastshow',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='podcastshow',
            name='image',
        ),
        migrations.RemoveField(
            model_name='podcastshow',
            name='total_episodes',
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='audio_url',
            field=models.URLField(default=django.utils.timezone.now, help_text='Link to MP3/audio file', verbose_name='Audio File URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='cover_image',
            field=models.URLField(blank=True, help_text='If blank, uses show image', null=True, verbose_name='Episode Cover Image'),
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='duration',
            field=models.CharField(default='00:00', help_text='Format: MM:SS or HH:MM:SS', max_length=20, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='file_size',
            field=models.CharField(blank=True, help_text='e.g., 25.5 MB', max_length=20, null=True, verbose_name='File Size'),
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='guest',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Guest(s)'),
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='host',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Host'),
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='season_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Season Number'),
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to YouTube/Vimeo or embedded video', null=True, verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/', verbose_name='Program Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('read', 'Lu'), ('replied', 'Répondu'), ('archived', 'Archivé')], default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Subject'),
        ),
        migrations.DeleteModel(
            name='PodcastEpisode',
        ),
    ]
