# Generated by Django 4.2.19 on 2026-02-07 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_advertisement_blog_team_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='written_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Written By'),
        ),
        migrations.AlterField(
            model_name='podcastshow',
            name='cover_image',
            field=models.URLField(blank=True, help_text='If blank, uses show image', null=True, verbose_name='Episode Cover Image Link'),
        ),
    ]
