# Generated by Django 4.2.19 on 2026-02-07 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_article_written_by_alter_podcastshow_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='written_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Written By'),
        ),
    ]
