# Generated by Django 6.0.1 on 2026-02-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_article_written_by_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastshow',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PodcastShow/', verbose_name='Image'),
        ),
    ]
