# Generated by Django 6.0.1 on 2026-02-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_podcastshow_cover_image_podcastshow_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastshow',
            name='image',
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='cover_image',
            field=models.URLField(blank=True, help_text='If blank, uses show image', null=True, verbose_name='Episode Cover Image Link'),
        ),
    ]
