# Generated by Django 6.0.1 on 2026-02-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_podcastshow_image_podcastshow_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(verbose_name='Sub content'),
        ),
    ]
