# Generated by Django 6.0.1 on 2026-02-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_article_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastshow',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='podcastshow',
            name='listen_count',
        ),
        migrations.RemoveField(
            model_name='podcastshow',
            name='season_number',
        ),
    ]
