# Generated by Django 6.0.1 on 2026-02-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_podcastshow_file_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcastshow',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Podcast Show', 'verbose_name_plural': 'Podcast Shows'},
        ),
        migrations.RemoveField(
            model_name='podcastshow',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='podcastshow',
            name='featured_description',
        ),
        migrations.RemoveField(
            model_name='podcastshow',
            name='featured_title',
        ),
        migrations.RemoveField(
            model_name='podcastshow',
            name='is_featured',
        ),
    ]
