# Generated by Django 6.0.1 on 2026-02-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_podcastshow_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastshow',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PodcastShow/', verbose_name='PodcastShow Image'),
        ),
    ]
