# Generated by Django 6.0.1 on 2026-02-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_podcastshow_cover_image_podcastshow_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Cammunity Title')),
                ('description', models.TextField(verbose_name='Cammunity Description')),
                ('image', models.ImageField(upload_to='Cammunity/', verbose_name='Cammunity Image')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Detailed Content')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Video URL (YouTube/Vimeo)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Community',
                'verbose_name_plural': 'Communities',
                'ordering': ['title', '-created_at'],
            },
        ),
    ]
