# Generated by Django 6.0.1 on 2026-02-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order of Display'),
        ),
    ]
