# Generated by Django 6.0.1 on 2026-02-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_community_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
