# Generated by Django 6.0.1 on 2026-02-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_community_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='slug',
        ),
    ]
