# Generated by Django 4.2.19 on 2026-02-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article Comment', 'verbose_name_plural': 'Article Comments'},
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Approved'),
        ),
    ]
