# Generated by Django 4.2.19 on 2026-02-12 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_article_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
