# Generated by Django 6.0.1 on 2026-02-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_article_options_remove_article_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
    ]
