# Generated by Django 6.0.1 on 2026-02-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_article_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='link',
        ),
    ]
