# Generated by Django 6.0.1 on 2026-02-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_blog_image_url_remove_blog_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.RemoveField(
            model_name='team',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='team',
            name='order',
        ),
    ]
