# Generated by Django 6.0.1 on 2026-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_team_options_remove_team_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order of Display'),
        ),
    ]
