# Generated by Django 6.0.1 on 2026-02-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_team_options_team_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastshow',
            name='slug',
        ),
    ]
