# Generated by Django 6.0.1 on 2026-02-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_podcastshow_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='video',
        ),
        migrations.AlterField(
            model_name='community',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(verbose_name='SubContent'),
        ),
    ]
