# Generated by Django 6.0.1 on 2026-02-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_community_video_alter_community_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastshow',
            name='image',
        ),
    ]
