# Generated by Django 6.0.1 on 2026-02-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_podcastshow_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastshow',
            name='published_date',
        ),
    ]
