# Generated by Django 6.0.1 on 2026-09-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_podcastshow_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ads/videos/', verbose_name='Ad Video'),
        ),
    ]
