# Generated by Django 6.0.1 on 2026-09-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_advertisement_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
    ]
