# Generated by Django 6.0.1 on 2026-09-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_blog_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blogs/videos/', verbose_name='Video'),
        ),
    ]
